name: apply-org-policy

on:
  workflow_dispatch:
    inputs:
      repos_csv:
        description: "Optional owner/repo list comma-separated to also label/protect"
        required: false

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Auth gh
        env:
          GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
        run: |
          gh --version
          unset GITHUB_TOKEN
          echo "$GH_TOKEN" | gh auth login --with-token
          gh auth status

      - name: Set env
        run: echo "ORG_NAME=${{ secrets.ORG_NAME }}" >> $GITHUB_ENV

      - name: Org settings
        run: bash github/scripts/org-settings.sh

      - name: Org ruleset
        run: bash github/scripts/org-ruleset.sh

      - name: Per-repo label + protection (optional)
        if: ${{ inputs.repos_csv != '' }}
        run: |
          IFS=',' read -ra REPOS <<< "${{ inputs.repos_csv }}"
          for r in "${REPOS[@]}"; do
            bash github/scripts/sync-labels.sh "$r"
            bash github/scripts/repo-branch-protect.sh "$r" main
          done