name: apply-org-policy
on:
  workflow_dispatch:
    inputs:
      repos_csv:
        description: "owner/repo comma-separated (optional)"
        required: false

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Use PAT for gh
        env:
          ORG_ADMIN_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
        run: |
          unset GITHUB_TOKEN
          echo "GH ready"; gh --version
          # expose for later steps
          echo "GH_TOKEN=$ORG_ADMIN_TOKEN" >> $GITHUB_ENV

      - name: Sanity check identity
        run: |
          echo "Actor:" $(gh api user --jq .login)
          echo "Org  :" $(gh api orgs/${{ secrets.ORG_NAME }} --jq .login)

      - name: Set env
        run: echo "ORG_NAME=${{ secrets.ORG_NAME }}" >> $GITHUB_ENV

      - name: Org settings
        run: bash github/scripts/org-settings.sh

      - name: Org ruleset
        run: bash github/scripts/org-ruleset.sh

      - name: Per-repo label + protection (optional)
        if: ${{ inputs.repos_csv != '' }}
        run: |
          IFS=',' read -ra REPOS <<< "${{ inputs.repos_csv }}"
          for r in "${REPOS[@]}"; do
            bash github/scripts/sync-labels.sh "$r"
            bash github/scripts/repo-branch-protect.sh "$r" main
          done