name: Apply Org Policy
on:
  workflow_dispatch:
    inputs:
      only_private:
        description: "Protect only private repos (true/false)"
        required: false
        default: "false"

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y jq

      - name: Auth
        env: { ORG_ADMIN_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }} }
        run: |
          unset GITHUB_TOKEN
          echo "GH_TOKEN=$ORG_ADMIN_TOKEN" >> $GITHUB_ENV
          gh --version
          echo "Actor: $(gh api user --jq .login)"
          echo "Org  : $(gh api orgs/${{ github.repository_owner }} --jq .login)"

      - name: List repos
        id: list
        run: |
          gh repo list "${{ github.repository_owner }}" --json name,visibility -L 200 \
            | jq -r '.[] | "\(.visibility)|${{ github.repository_owner }}/\(.name)"' > repos.txt
          cat repos.txt

      - name: Protect + labels
        run: |
          while IFS="|" read -r vis full; do
            if [[ "${{ inputs.only_private }}" == "true" && "$vis" != "private" ]]; then continue; fi
            echo ">> $full"
            bash github/scripts/repo-branch-protect.sh "$full" main
            bash github/scripts/sync-labels.sh "$full"
          done < repos.txt